name: Documentation Tests

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ubuntu-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ubuntu-go-

      - name: Tests
        run: go test -v ./...
